name = "QueryBridge"
version = "0.1.0"
defaultTargets = ["querybridge"]

[[lean_lib]]
name = "QueryBridge"
srcDir = "src"

[[lean_exe]]
name = "querybridge"
root = "Main"

# Documentation generation support
[dependencies]
DocGen4 = { git = "https://github.com/leanprover/doc-gen4", rev = "main" }

# Documentation configuration
[configuration]
[configuration.doc]
title = "QueryBridge Documentation"
description = "A tool for translating GraphQL queries to XSB Datalog"